### ISSUE TITLE
关于背包钛矿解锁科技

### ISSUE THREAD

**Issue by affairgit** [tph85666031/DSPConsole#1]
你好，我测试了一下此mod，mod文件是在Thunderstore下载的，我测试了元数据倍率与轻松开局的功能，元数据倍率没有问题。但是轻松开局我遇到了问题，在解锁电磁学时，可以正常解锁机甲科技和宇宙探索科技等。而当我获取了物品Id为1004的钛矿时，并没有解锁行星物流，相应的钛矿数量为99时也无事发生。于是，我使用沙盒模式进行检测发现，要在解锁电磁学之前就获得钛矿，才能实现mod功能，解锁相应的科技。我也尝试了先关闭轻松开局再打开但是仍然没用。总之，解锁电磁学之前没法获得钛矿啊，这个功能是不是有bug啊。是只检测一次解锁电磁学的时候的原因吗？若先关闭轻松开局解锁电磁学，再打开轻松开局，宇宙探索也同样无法解锁了。

**Comment by tph85666031** [comment]
地中海上挖石头

**Comment by affairgit** [comment]
母星上炼制石矿不是只能获得硅石吗，是我记错了吗

**Comment by tph85666031** [comment]
@affairgit 让机甲手动挖

**Comment by affairgit** [comment]
受教了
